function toggleOptions(id) {
    const section = document.getElementById(id);
    section.style.display = section.style.display === "block" ? "none" : "block";
    document.getElementById("answerBox").innerHTML = "";
  }
  
  function showAnswer(code) {
    const answers = {
      islam1: "Dalam Islam, meskipun paham ateisme sangat dilarang dan ditentang, umat Muslim diajarkan untuk tidak memaksa seseorang masuk dalam Islam atau meyakini agama tertentu, termasuk menghormati keyakinan lain. Sebagai Muslim dan warga negara yang baik, kita tidak boleh memaksa ateis untuk beragama, tetapi harus waspada jika mereka menyebarkan pahamnya secara memaksa atau memengaruhi orang lain menjadi ateis. Islam mengajarkan toleransi, namun juga kewaspadaan terhadap penyebaran ideologi yang bertentangan dengan ajaran agama.",
      kristen1: "Ateis adalah Pandangan yang mempercayai bahwa Tuhan itu tidak ada. Ada beberapa pandangan Gereja terhadap hal ini : Sebagai mahluk hidup semua manusia adalah ciptaan Tuhan Kejadian 1:27. Kristus dalam pelayanannya di Dunia sering sekali menjadi pembela bagi orang-orang yang dianggap hina dan berdosa, seperti;  Wanita yang berjinah (Yoh 8), Zakheus Pemungut cukai (Lukas 19), Bahkan yang tidak percaya padaNya (Markus 9:19).Kematian Kristus bukan ekslusif dimiliki orang Kristen, tetapi semua orang, 2 Korintus 5:15,16.Keselamatan manusia bukan hasil usahanya tetapi adalah pemberian atau hak Tuhan (Efesus 2:8,9).",
      katolik1: "- Ateisme bisa dianggap sebagai bentuk penolakan terhadap agama, yang menurut sejarah filsafat, dimulai dari pemikiran bahwa agama adalah opium atau pelarian dari penderitaan. - Namun, agama Katolik menekankan bahwa iman bukan sekadar pelarian, melainkan panggilan hidup yang mendalam dan memiliki dimensi mistik.",
      hindu1: "Dalam agama Hindu, penganut ateisme tetap dihormati selama mereka tidak merusak atau mengganggu keyakinan agama lain, termasuk Hindu. Prinsip utama dalam Hindu adalah Tri Hita Karana, yaitu tiga hubungan harmonis untuk mencapai kebahagiaan: hubungan dengan Tuhan, dengan sesama manusia, dan dengan alam. Selama seorang ateis menjaga etika, bersikap sopan, tidak merugikan orang lain, dan hidup selaras dengan sesama, maka keberadaannya dapat diterima dalam pandangan Hindu.",
      budha1: "Secara umum, terdapat dua konsep besar dalam perilaku keagamaan: di Asia cenderung politeistik atau simbolik (seperti dewi air, matahari), sedangkan di wilayah Arab dan Israel lebih monoteistik, yaitu menyembah satu Tuhan. Konsep ateisme berkembang dari sekularisme—keinginan untuk bebas dari sistem dan aturan agama, termasuk ritual dan kewajiban finansial seperti donasi. Di Eropa misalnya, penganut agama tertentu dipotong pajak untuk kepentingan keagamaan, sehingga sebagian orang memilih menjadi ateis karena merasa agama tidak memberi manfaat praktis. Namun, hal ini sulit diterapkan di Indonesia karena landasan negara, yaitu Pancasila, secara eksplisit menegaskan kepercayaan kepada Tuhan Yang Maha Esa.",
      islam2: " Karena Allah mengutus Nabi dan Rasul, dari Nabi adam AS hingga Nabi Muhammad SAW itu untuk menegakan ajaran Tauhid yang artinya bertuhan, dan mereka di utus sesuai dengan kaumnya, seperti Nabi Musa kepada kaum Bani Israil. Sampai pada Nabi terakhir yaitu Nabi Muhammad SAW mengajarkan kepada kita bahwa “Lailaahailallah” (Tiada tuhan selain Allah). Namun,  agama islam itu adalah agama yang “rahmatan lil alamin” Hal ini tertuang dalam surat Al Kafirun ayat 6 yang berbunyi “Lakum diinukum waliyadiin” (Untukmu agama mu dan untukku agama ku)",
      kristen2: "Tentu ketika Mahasiswa kami (pendeta) belajar tentang agama-agama dan kepercayaan di Dunia, termasuk Ateis. Mazmur 14:1 ayat ini membuktikkan adanya atheis sejak dahulu",
      katolik2: "Dalam katolik tidak ada ajaran khusus mengenai Ateisme",
      hindu2: "Tidak ada ajaran khusus, tetapi jika ajaran yang menyatakan bahwa dia tidak mengakui otoritas Hindu, ada. Yaitu, Nastika. Aliran ini tidak mengakui Weda sebagai kitabnya.",
      budha2: "Di Buddhis tidak secara gamblang menyatakan tidak beragama itu salah. Mungkin belum ditemukan kebenaran sejati dalam dirinya. Kita tidak boleh bilang dia itu salah. Namun sang Buddha bilang dalam suatu ceramah, bahwa daun yang beliau pegang bisa mengantarkan menuju nibbana, dibanding daun'' yang lain di hutan itu. Yang berarti kebenaran hadir dari pola pikir masing''. Mungkin orang atheis belum bertemu daun yang tepat untuk mencerahkan dia.",
    };
    document.getElementById("answerBox").innerText = answers[code] || "Belum ada jawaban.";
  }